blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

app_name = "blog"
urlpatterns = [
    path(
        r'',
        views.IndexView.as_view(),
        name='index'),
    path(
        r'page/<int:page>/',
        views.IndexView.as_view(),
        name='index_page'),
    path(
        r'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html',
        views.ArticleDetailView.as_view(),
        name='detailbyid'),
    path(
        r'category/<slug:category_name>.html',
        views.CategoryDetailView.as_view(),
        name='category_detail'),
    path(
        r'category/<slug:category_name>/<int:page>.html',
        views.CategoryDetailView.as_view(),
        name='category_detail_page'),
    path(
        r'author/<author_name>.html',
        views.AuthorDetailView.as_view(),
        name='author_detail'),
    path(
        r'author/<author_name>/<int:page>.html',
        views.AuthorDetailView.as_view(),
        name='author_detail_page'),
    path(
        r'tag/<slug:tag_name>.html',
        views.TagDetailView.as_view(),
        name='tag_detail'),
    path(
        r'tag/<slug:tag_name>/<int:page>.html',
        views.TagDetailView.as_view(),
        name='tag_detail_page'),
    path(
        'archives.html',
        cache_page(
            60 * 60)(
            views.ArchivesView.as_view()),
        name='archives'),
    path(
        'links.html',
        views.LinkListView.as_view(),
        name='links'),
    path(
        r'upload',
        views.fileupload,
        name='upload'),
    path(
        r'clean',
        views.clean_cache_view,
        name='clean'),
]

djangoblog/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.urls import re_path
from haystack.views import search_view_factory

from blog.views import EsSearchView
from djangoblog.admin_site import admin_site
from djangoblog.elasticsearch_backend import ElasticSearchModelSearchForm
from djangoblog.feeds import DjangoBlogFeed
from djangoblog.sitemap import ArticleSiteMap, CategorySiteMap, StaticViewSitemap, TagSiteMap, UserSiteMap

sitemaps = {

    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'
handle403 = 'blog.views.permission_denied_view'

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]
urlpatterns += i18n_patterns(
    re_path(r'^admin/', admin_site.urls),
    re_path(r'', include('blog.urls', namespace='blog')),
    re_path(r'mdeditor/', include('mdeditor.urls')),
    re_path(r'', include('comments.urls', namespace='comment')),
    re_path(r'', include('accounts.urls', namespace='account')),
    re_path(r'', include('oauth.urls', namespace='oauth')),
    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
            name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^feed/$', DjangoBlogFeed()),
    re_path(r'^rss/$', DjangoBlogFeed()),
    re_path('^search', search_view_factory(view_class=EsSearchView, form_class=ElasticSearchModelSearchForm),
            name='search'),
    re_path(r'', include('servermanager.urls', namespace='servermanager')),
    re_path(r'', include('owntracks.urls', namespace='owntracks'))
    , prefix_default_language=False) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/share_layout/adsense.html
<aside id="text-2" class="widget widget_text"><h3 class="widget-title">Google AdSense</h3>
    <div class="textwidget">

        {{ GOOGLE_ADSENSE_CODES }}
    </div>
</aside>

templates/share_layout/base.html
{% load static %}
{% load cache %}
{% load i18n %}
{% load compress %}
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie ie7" lang="zh-CN"
      prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8" lang="zh-CN"
      prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
<![endif]-->
<!--[if !(IE 7) & !(IE 8)]><!-->
<html lang="zh-CN" prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
<!--<![endif]-->
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width"/>
    {% block header %}
    {% endblock %}
    <link rel="profile" href="http://gmpg.org/xfn/11"/>

    <!--[if lt IE 9]>
    <script src="{% static 'blog/js/html5.js' %}" type="text/javascript"></script>
    <![endif]-->

    <link rel="alternate" type="application/rss+xml" title="{{ SITE_NAME }} &raquo; Feed"
          href="/feed"/>
    <link rel='stylesheet preload' as="font" id='twentytwelve-fonts-css'
          href='{% static 'blog/fonts/fonts.css' %}'
          type='text/css' media='all'/>
    <link rel="dns-prefetch" href="//cdn.mathjax.org"/>
    {% compress css %}

        <link rel='stylesheet' id='twentytwelve-style-css' href='{% static 'blog/css/style.css' %}' type='text/css'
              media='all'/>
        <link href="{% static 'blog/css/oauth_style.css' %}" rel="stylesheet">
        {% comment %}<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>{% endcomment %}
        <!--[if lt IE 9]>
        <link rel='stylesheet' id='twentytwelve-ie-css'  href='{% static 'blog/css/ie.css' %}' type='text/css' media='all' />
        <![endif]-->
        <link rel="stylesheet" href="{% static 'pygments/default.css' %}"/>
        <link rel="stylesheet" href="{% static 'blog/css/nprogress.css' %}">
        {% block compress_css %}
        {% endblock %}
    {% endcompress %}
    {% if GLOBAL_HEADER %}
        {{ GLOBAL_HEADER|safe }}
    {% endif %}
</head>

<body class="home blog custom-font-enabled">
<div id="page" class="hfeed site">
    <header id="masthead" class="site-header" role="banner">
        <hgroup>
            <h1 class="site-title"><a href="/" title="{{ SITE_NAME }}" rel="home">{{ SITE_NAME }}</a>
            </h1>
            <h2 class="site-description">{{ SITE_DESCRIPTION }}</h2>
        </hgroup>
        {% load i18n %}


{#        <div class="i18n-selector">#}
{#            <form action="{% url 'set_language' %}" method="post" id="i18n-form">{% csrf_token %}#}
{#                <input name="next" type="hidden" value="{{ redirect_to }}">#}
{#                <select name="language" class="i18n-select" >#}
{#                    {% get_current_language as LANGUAGE_CODE %}#}
{#                    {% get_available_languages as LANGUAGES %}#}
{#                    {% get_language_info_list for LANGUAGES as languages %}#}
{#                    {% for language in languages %}#}
{#                        <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>#}
{#                            {{ language.name_local }} ({{ language.code }})#}
{#                        </option>#}
{#                    {% endfor %}#}
{#                </select>#}
{#                                <input type="submit" value="Go">#}
{#            </form>#}
{#        </div>#}


        {% include 'share_layout/nav.html' %}


    </header><!-- #masthead -->
    <div id="main" class="wrapper">

        {% block content %}
        {% endblock %}


        {% block sidebar %}
        {% endblock %}


    </div><!-- #main .wrapper -->
    {% include 'share_layout/footer.html' %}
</div><!-- #page -->

</body>
<footer>
    <script src="//cdn.bootcss.com/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    {% compress js %}
        <script type="text/javascript" src="{% static 'blog/js/jquery-3.6.0.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'blog/js/nprogress.js' %}"></script>
        <script src="{% static 'blog/js/blog.js' %}" type="application/javascript"></script>
        <script src="{% static 'blog/js/navigation.js' %}" type="application/javascript"></script>
        <script src="{% static 'mathjax/js/mathjax-config.js' %}" type="application/javascript"></script>
        {% block compress_js %}
        {% endblock %}
    {% endcompress %}
    {% block footer %}
    {% endblock %}
</footer>
</html>

templates/share_layout/base_account.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <meta name="robots" content="noindex">
    <title>{{ SITE_NAME }} | {{ SITE_DESCRIPTION }}</title>
    <link href="{% static 'account/css/account.css' %}" rel="stylesheet">
    {% load compress %}
    {% compress css %}
        <!-- Bootstrap core CSS -->
        <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'blog/css/oauth_style.css' %}" rel="stylesheet">
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <link href="{% static 'assets/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">
        <!-- TODC Bootstrap core CSS -->
        <link href="{% static 'assets/css/todc-bootstrap.min.css' %}" rel="stylesheet">
        <!-- Custom styles for this template -->
        <link href="{% static 'assets/css/signin.css' %}" rel="stylesheet">
    {% endcompress %}
    {% compress js %}
        <script src="{% static 'assets/js/ie10-viewport-bug-workaround.js' %}"></script>
        <script src="{% static 'assets/js/ie-emulation-modes-warning.js' %}"></script>
    {% endcompress %}
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
{% block content %}
{% endblock %}

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->

</body>
    <script type="text/javascript" src="{% static 'blog/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'account/js/account.js' %}" type="text/javascript"></script>
</html>

templates/share_layout/footer.html
<footer id="colophon" role="contentinfo">
    <div class="site-info" style="text-align: center">
        Copyright&copy;&nbsp;{{ CURRENT_YEAR }}&nbsp;
        <a href="/" target="blank">{{ SITE_NAME }}</a>
        &nbsp;|&nbsp;

        <a href="/sitemap.xml" title="SiteMap" target="_blank">
            SiteMap
        </a>
        &nbsp;|&nbsp;
        <a href="/feed" title="RSS Feed" target="_blank">
            RSS Feed
        </a>
        &nbsp;|&nbsp;
        <a href="/links.html" title="友情链接" rel="nofollow" target="_blank">
            友情链接
        </a>
        |&nbsp; Hosting On&nbsp;
        <a href="https://www.linode.com/?r=b0d38794d05ef8816b357a929106e89b7c6452f9" target="blank" rel="nofollow">Linode</a>

        |&nbsp;
        <a href="https://tongji.baidu.com/sc-web/3478620/home/ico?siteId=11261596" target="_blank"
           rel="nofollow">百度统计</a>

    </div>
    <div class="site-info" style="text-align: center">
        Powered by
        <a href="https://www.djangoproject.com/" rel="nofollow" target="blank">Django</a>
        &nbsp;|&nbsp;
        <a href="https://github.com/liangliangyy/DjangoBlog" rel="nofollow" target="blank">liangliangyy</a>
        |
        <a href="https://www.lylinux.net" target="blank">lylinux</a>
        |
        本页面加载耗时:<!!LOAD_TIMES!!>s
    </div>
    {% if BEIAN_CODE %}
        <div class="site-info" style="text-align: center">
            <a href="https://beian.miit.gov.cn/" rel="nofollow" target="_blank">
                <p style=" height:20px;line-height:20px;margin: 0px 0px 0px 5px; color:#939393;">
                    {{ BEIAN_CODE }}
                </p>
            </a>
            {% if BEIAN_CODE_GONGAN and SHOW_GONGAN_CODE %}
                {{ BEIAN_CODE_GONGAN |safe }}
            {% endif %}
        </div>
    {% endif %}
    {% if ANALYTICS_CODE %}
        {{ ANALYTICS_CODE| safe }}
    {% endif %}
    {% if GLOBAL_FOOTER %}
        {{ GLOBAL_FOOTER|safe }}
    {% endif %}
</footer><!-- #colophon -->

templates/share_layout/nav.html
{% load i18n %}

<nav id="site-navigation" class="main-navigation" role="navigation">
    <div class="menu-%e8%8f%9c%e5%8d%95-container">
        <ul id="menu-%e8%8f%9c%e5%8d%95" class="nav-menu">
            <li id="menu-item-3498"
                class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-3498">
                <a href="/">{% trans 'index' %}</a></li>

            {% load blog_tags %}
            {% query nav_category_list parent_category=None as root_categorys %}
            {% for node in root_categorys %}
                {% include 'share_layout/nav_node.html' %}
            {% endfor %}
            {% if nav_pages %}
                {% for node in nav_pages %}

                    <li id="menu-item-{{ node.pk }}"
                        class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-{{ node.pk }}">
                        <a href="{{ node.get_absolute_url }}">{{ node.title }}</a>
                    </li>
                {% endfor %}
            {% endif %}
            <li class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children">

                <a href="{% url "blog:archives" %}">{% trans 'Article archive' %}</a>
            </li>
        </ul>
    </div>
</nav><!-- #site-navigation -->

templates/share_layout/nav_node.html
<li id="menu-item-{{ node.pk }}"
    class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-has-children menu-item-{{ node.pk }}">
    <a href="{{ node.get_absolute_url }}">{{ node.name }}</a>
    {% load blog_tags %}
    {% query nav_category_list parent_category=node as child_categorys %}
    {% if child_categorys %}

        <ul class="sub-menu">
            {% for child in child_categorys %}
                {% with node=child template_name="share_layout/nav_node.html" %}
                    {% include template_name %}
                {% endwith %}
            {% endfor %}

        </ul>
    {% endif %}
</li>